### PR TITLE
Update Introductions.md with my favourite topping

### PR DESCRIPTION
**Pull request by jmc-alan-turing**
Add my favourite pizza topping

### CODE REVIEW

**Comment by jmc-alan-turing** [comment]
@cassgvp

**Comment by jmc-alan-turing** [comment]
@RahmaJ4 you were not supposed to add a commit to someone else's pull request, the task was to fork the repository, commit your changes there, then submit your own pull request...

**Comment by cassgvp** [comment]
@jmc-alan-turing looking into this conflict now!

**Review by cassgvp — APPROVED** [review]

**Comment by malvikasharan** [comment]
@jmc-alan-turing and @RahmaJ4 - this is an interesting Pull Request. For the assignment, yes we were asking each of you to create separate PR. But! We can indeed work on same Pull Request, such as we have managed to do here.

**Pull request merged**
